set_property IOSTANDARD LVCMOS33 [get_ports clk_ADC]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_En]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN H4 [get_ports clk_100MHz]
set_property PACKAGE_PIN D1 [get_ports {TMDS_Tx_Data_P[2]}]
set_property PACKAGE_PIN E2 [get_ports {TMDS_Tx_Data_P[1]}]
set_property PACKAGE_PIN G1 [get_ports {TMDS_Tx_Data_P[0]}]
set_property PACKAGE_PIN C5 [get_ports clk_ADC]
set_property PACKAGE_PIN G4 [get_ports TMDS_Tx_Clk_P]
set_property PACKAGE_PIN J4 [get_ports ADC_En]
set_property PACKAGE_PIN C3 [get_ports {key[0]}]
set_property PACKAGE_PIN M4 [get_ports {key[1]}]


set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Tx_Data_P[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Tx_Data_P[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Tx_Data_P[0]}]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_Tx_Clk_P]

set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_data[0]}]
set_property PACKAGE_PIN J3 [get_ports {ADC_data[0]}]
set_property PACKAGE_PIN J2 [get_ports {ADC_data[1]}]
set_property PACKAGE_PIN D12 [get_ports {ADC_data[2]}]
set_property PACKAGE_PIN E12 [get_ports {ADC_data[3]}]
set_property PACKAGE_PIN F12 [get_ports {ADC_data[4]}]
set_property PACKAGE_PIN C11 [get_ports {ADC_data[5]}]
set_property PACKAGE_PIN H12 [get_ports {ADC_data[7]}]
set_property PACKAGE_PIN H11 [get_ports {ADC_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_DAC]

set_property PACKAGE_PIN M1 [get_ports clk_DAC]
